### ISSUE TITLE
erb - use html comments to comment out lines rather than erb tags

### ISSUE THREAD

**Issue by dylan-chong** [preservim/nerdcommenter#364]
The problem with using `<%# ... %>` To comment out a line is that if the line contains `<% content %>` already, then we will end up with:

```eruby
<%# <% content %> %>
```

The second `%>` will be typed out  literally in the template.

 If we use HTML `<!-- -->`  (which is what sublime text does) then we don't have to worry about this issue

**Comment by tom-barone** [comment]
```vim
let g:NERDAltDelims_eruby = 1
```

This will switch to use `<!--` instead of `<%#`.
