### ISSUE TITLE
Migrate repository to shared org namespace

### ISSUE THREAD

**Issue by alerque** [preservim/nerdcommenter#400]
Since sometime in 2016 (see #236) I've been the ~~primary~~ sole maintainer of this plugin, the only developer actively managing the repository, helping PR's to get merged, attending to bugs, and tinkering with new features. It hasn't been a huge issue for me to have it in another namespace and I certainly haven't wanted it in my personal namespace because, having not developed in in the first place, I don't feel like I am the owner.

However as time goes on more issues come up that make it hard to maintain a plugin without any ownership of the repository. Github is constantly adding features, and I could do a lot to help the PR workflow if I had more access. The repository owner remains completely uninvolved and also unreachable, making it impractical to ask him for every change.

Additionally I've run across more good plugins that have stagnated because their initial developers have moved on to other things. The community continues to use them and even finds and fixes bugs, but the PRs just build up because the repository owners are elsewhere. I've started taking care of a few of these, including `vim-ledger`, `vim-pandoc`, and others. The latest one I ran across and picked up maintenance for is [tagvim](https://github.com/majutsushi/tagbar/issues/549).

I think it is time to move this plugin to a namespace where I have some access to tweak the settings, setup CI jobs, etc. This will avoid the appearance of trying to take over 'ownership' (credit still goes to @scrooloose for creating this plugin) but give some leeway to maintain it properly. I think this will also encourage community contributions in the end as it will be more apparent that it is a group effort, not one person's baby.

To that end I have created the an org namespace @preservim where this and possibly later other plugins I'm helping to maintain could be hosted. **I would like to request this plugin be migrated to that namespace.** @scrooloose I have invited you to the org. Please let me know how this idea sits with you.

Note that migration will not break any of the existing links, credits, git clones, or anything because GitHub keeps redirects from the old namescpace.

**Comment by wsdjeg** [comment]
see my previous comment, https://github.com/majutsushi/tagbar/issues/549#issuecomment-544237548

**Comment by alerque** [comment]
@wsdjeg Your comment on the other project only suggested that the original namespace would be "easier for searching", but I noted that GitHub automatically adds redirects from the old namespaces so that search results and even existing git clones do not lose their connection to the project, everything follows the migration pretty smoothly. I can't think of any downside related to searching, and you didn't respond there. Did you still have a concern related to this?

Note that one reason to get this migration done is that I would like to setup CI jobs to lint and validate PRs, but I am unable to do that. In a shared org namespace it would be easier to setup the permissions in a way that kept the original author in the loop and credited but let me mess with the repository settings to keep moving things forward. At this point it has been 3 years that I've been doing _all_ the maintenance work on this plugin and if my track record both on the plugin itself and with the community interacting in issues does not speak for itself, I don't have much else to appeal to. I can understand @scrooloose not having time or interest to work on this, but I think he can probably trust me with managing the repository settings too.

**Comment by alerque** [comment]
*Status update:* I did hear back from Martin via email on the 28th saying he would "do this in the next couple of days".

**Comment by scrooloose** [comment]
@alerque Sorry for the delay on this. I have created a new `vim-nerdcommenter` org and transferred the repo to that. I have invited you to the org with `owner` permissions.

I am very happy to pass the "ownership" over to you - rightly so since you have been doing the work for the last few years and have more than proven yourself to be safe and reliable. Really I should have done this years ago.

This is a project that I started 15 years ago while at university and I'm glad to see it is still alive and useful! I'm glad to leave it in your hands.

**Comment by alerque** [comment]
Thanks @scrooloose. I have gone ahead and moved this into @preservim — to which you have an outstanding invitation to join by the way. Additionally even if you don't join that org I've marked you as having admin rights on this repository so you would be able to appoint other collaborators in the future if I get hit by a bus.

**Comment by scrooloose** [comment]
@alerque I have joined the org. Nice to know I can still get involved should the urge return. Thanks!  :-)
