### ISSUE TITLE
[Feature request]  CommentFrame.vim style comment

### ISSUE THREAD

**Issue by yutakatay** [preservim/nerdcommenter#418]
I love [CommentFrame's](https://github.com/cometsong/CommentFrame.vim
) comment since I found it on [Reddit](https://www.reddit.com/r/vim/comments/f0wam8/found_a_little_known_awesome_plugin_called/)

But CommentFrame is too old.  (eg. Mapping cannot be changed)

Could you support this style comment?

**Comment by alerque** [comment]
Ug, that reminds me too much of Perl code I hacked on in the '90s! Don't get me wrong I love Perl, but the comment style is not my personal favorite. Hence I probably wont be investing a bunch of time to add this feature myself.

That being said I don't see any reason to exclude it. If somebody wants to contribute support as an extra style I'd  be happy to see it supported here. It would need to play nicely with the comment/uncomment functions and work similarly to the the existing fancy style.

If such a PR comes along I'll be happy to review and help it get included.

**Comment by yutakatay** [comment]
Thank you for your replay.

Ok. I understood :wink:
