### ISSUE TITLE
my key mappings have stopped working after the latest update

### ISSUE THREAD

**Issue by codehia** [preservim/nerdcommenter#434]
I had the following key mapping:
```
nmap <C-_>   <Plug>NERDCommenterToggle
vmap <C-_>   <Plug>NERDCommenterToggle<CR>gv
```

They have stopped working, any help regarding this will be much appreciated. Thanks

**Comment by alerque** [comment]
Checking `:help NERDCommenterToggle` (and code) I see the mappings are defined with `<plug>` lower-case. This hasn't changed in the plugin *ever*, and the last code that changed that moved even where and how in the plugin that was defined was changed in 2011. So whatever your "last update" was I don't think it's this plugin that changed.

That being said in my head at least `<plug>`/`<Plug>` should have been interchangeable. I thought it was case insensitive like `<Silent>` or `<Cr>` are. I don't know when or if that changed.

Are you sure you didn't just overhaul your mappings and change the case on this?

**Comment by codehia** [comment]
Sorry for the delay in response, the issue is with the terminal I'm using, the same key mapping works with tilix but fails with Hyper.js any solutions for this? Thanks

**Comment by alerque** [comment]
Use a better terminal? File a bug report with the terminal that's not handling key-codes properly? Picks some key combo that it happens to work okay on?
