### ISSUE TITLE
Treesitter integration

### ISSUE THREAD

**Issue by weilbith** [preservim/nerdcommenter#436]
I would like to ask what you think about adding support for the recently added treesitter integration? Features likes comment current scope/node or uncomment current comment block the cursor is inside. The first easy could be already easily achieved via `nvim-treesitter` it's text objects. But uncomment the current comment block would be awesome. A typical use-case would be that you have commented a code-block for some debugging or so and then want to uncomment it again. For now it is quite cumbersome to achieve that (if you are happy you can use the paragraph text object to visually select it).
Thanks for any feedback about the idea.

**Comment by alerque** [comment]
This sounds like a great idea and I'd love to see it happen. It's unlikely I'll have the time to implement it myself any time soon but I'd be happy to help facilitate any other contributor that wanted to work on this get their PR in shape and merged.

**Comment by weilbith** [comment]
An easy solution for the mentioned "problem" is just to use the `@comment.outer` text object of treesitter-textobjects and define mapping to visually select it. Then just go ahead with the normal comment related mappings as usual. 
I think there is not much to improve/do on this site here. Therefore closing this issue.
