### ISSUE TITLE
Issue commenter with React

### ISSUE THREAD

**Issue by lioaslan** [preservim/nerdcommenter#437]
## Purpose
Comment a component in React
## Action
`<leader>cc`
## Code before comment
```javascript
import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';

class PDFInvoice extends React.Component {
  render() {
    return (
      <Document>
        <Page>
          <View>
            <Text>abc</Text>
          </View>
        </Page>
      </Document>
    );
  }
}

export default PDFInvoice;
```
## Code when comment with NerdCommenter
```javascript
import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';

class PDFInvoice extends React.Component {
  render() {
    return (
      <Document>
        /*<Page>*/
          //<View>
          //  <Text>abc</Text>
          //</View>
        /*</Page>*/
      </Document>
    );
  }
}

export default PDFInvoice;
```
Thís code make error
## It should be:
```javascript
import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';

class PDFInvoice extends React.Component {
  render() {
    return (
      <Document>
        {/* <Page>
          <View>
            <Text>abc</Text>
          </View>
        </Page> */}
      </Document>
    );
  }
}

export default PDFInvoice;
```
It should have a bracket `{}` at begin and end of block code I want to comment

**Comment by chris542** [comment]
<leader>ca changes to different comment types.
![image](https://user-images.githubusercontent.com/17423698/100955525-901cfb00-357b-11eb-9d86-23f18dff0813.png)
Then use <leader>cc

**Comment by alerque** [comment]
If Chris's suggestion doesn't answer this for you feel free to let us know, but I think that is the proper solution. It sounds like you just wanted the alternate comment syntax. Note there is information in the documentation for how to use the alternate by default or even change the delimiters to your preference for a given file type in the documentation.

**Comment by lioaslan** [comment]
@alerque Chris's solution doesn't work with me and I try to find out how I can custom commenter by myself but I can't find it. Can you indicate it to me

**Comment by alerque** [comment]
I just tested it with your example and it works fine.

1. I copied the text in your initial post too a `foo.jsx` file.
2. Opened it in NeoVIM
3. Changed to the alternate comment syntax with `<leader>ca`
4. Used visual mode to select the text I see commented in your example.
5. Commented it with a minimal comment block using `<leader>cm`.

The result is what you show in your expected output.

**Comment by lioaslan** [comment]
Oh, my project use `.js` file for React. There're so many files so I can't convert to `.jsx` file

**Comment by alerque** [comment]
Not to be too callus, but that's your problem. The official VIM file type for React is `javascriptreact`. You either need to set your file extensions so it can be discovered, use modelines to override the filetype, set it manually, or manually change NerdCOMMENTER's comment type definition for `javascript` in your vim configs. This plugin is doing the right thing already. You are doing a non-standard thing, so working around the expected consequences of not using the right file type is on you.

Also just a reminder that (after you fix your file types) `<leader>cc` will toggle linewise comments, if you want a minimal block comment style use `<leader>cm`.

**Comment by LinuxIsCool** [comment]
Hopefully this is helpful. I solved this by setting custom delimiters on javascript files, then using <leader>ca to toggle between primary and alternative when working in jsx.

`let g:NERDCustomDelimiters = {'javascript': { 'left': '//', 'right': '', 'leftAlt': '{/* ', 'rightAlt': ' */}' }}`
