### ISSUE TITLE
comments wrong for .S file

### ISSUE THREAD

**Issue by nickdesaulniers** [preservim/nerdcommenter#438]
Not sure if this is a bug in nerdcommenter or vim, but it's common to have assembler source (.s) that is required to be preprocessed by the C preprocessor first. This is done to share constants via `#define` between C and ASM sources, for example.  The convention that compilers use is .S (capital s) to first invoke the preprocessor.  With nerdcommenter, using the hotkey to insert comments inserts an assembler comment, but I think it should insert a preprocessor comment `/* */` for .S files?

**Comment by alerque** [comment]
This plugin is only setup to operate on the level of VIM's `filetype` setting. A believe `.s` and `.S` files are going to have the same file type. Even if convention among users is to preprocess one and not the other, if that is not reflected in the filetypes you use it isn't going to be fixable here. You are welcome to setup an override for your assembly file type to use C style comments, but I don't see why we would change that for everybody.

If I'm wrong about that and there are two file types to work with then sure of course we could set that up.

**Comment by qianlv** [comment]
You can custom
example：
`let g:NERDCustomDelimiters = { 'asm' : {'left': '#'}}`

**Comment by nickdesaulniers** [comment]
The tricky aspect about assembler is that the token used for comments differs between target ISAs; some support more than one.  So to say "this one token is a comment for assembler" isn't precise. It depends on the target ISA AND whether the assembler needs to be preprocessed by the C preprocessor first.

**Comment by alerque** [comment]
As far as I'm reading this, we don't have a way to fix this for everybody because the filetype simply doesn't delineate the specific comment type needed. Since we do provide a way for people to override the defaults for their own use cases I think that's probably as far as we can go. I'm open to re-evaluating if somebody has a suggestion for improvement, but am closing this issue to reflect the current state.
