### ISSUE TITLE
Allow joining commented lines

### ISSUE THREAD

**Issue by chelmertz** [preservim/nerdcommenter#44]
If I have the following code:

``` php
// This is a multiline
// comment but it's a bit misaligned
```

I'd like to `VjJ` to select & join both lines and **have the second set of // removed**.

**Comment by alerque** [comment]
I don't know what's going on here—whether this was added at some point or whether there is a vim setting for this, but this works for me exactly as you describe. I disabled all my other plugins and this still works. It doesn't work for all comment styles, but at least for  `//` prefixed lines as in your demo already works.

Can somebody else look into this and see what's actually going on?
