### ISSUE TITLE
commenting closed folds

### ISSUE THREAD

**Issue by ces42** [preservim/nerdcommenter#443]
Actual behavior: When I press `\cc` (in normal) with the cursor on a closed fold, only the first line of the fold is commented. Same for `\c ` etc.
Expected behavior: I guess it would be more useful and intuitive if `\cc` etc. operated on the whole fold. At the moment this can be achieved by doing `V\cc` (which admittedly is very little extra work).

**Comment by alerque** [comment]
Thanks for the request, but this is a duplicate of #315. See [my comment there](https://github.com/preservim/nerdcommenter/issues/315#issuecomment-349241911) for why this is not practical to implement and some alternatives depending on the functionality you want. The short version is that we're just an action that operation in the way normal VIM actions operate: on the current cursor, line, or range.

**Comment by ces42** [comment]
Oh, sorry for re-raising a closed issue.
