### ISSUE TITLE
typescriptreact filetype issue

### ISSUE THREAD

**Issue by chris542** [preservim/nerdcommenter#448]
It seems like most of vim plugins detect react typescript filetype as : 'typescript.tsx'

But only nerdcommenter is using 'typescriptreact' file type. I had to force my vim to use 

au BufNewFile,BufRead *.jsx set filetype=javascriptreact
au BufNewFile,BufRead *.tsx set filetype=typescriptreact

And this causes so many other plugins to not recognize tsx / jsx files to perform correct behaviours.

For example,
w0rp/ale ALEFix doesn't recognize typescriptreact, hence doesn't allow me to use prettier.

typescriptreact gives wrong colour syntax when using some colorschemes.

Is it possible to either add "typescript.tsx" "javascript.jsx" or replace 'typescriptreact' and 'javascriptreact' ?

Thanks!

**Comment by alerque** [comment]
The `typescript.tsx` filetype was an unofficial workaround used by a number of plugins to hack in support by pretending tsx were `typescript` files and using the extra string to bolt on extra features before VIM had first class support for `typescriptreact` as a filetype. I realize there is still quite a bit of usage in the wild, but we're actually far from the only plugin that has adjusted to work the way upstream VIM and NeoVIM have chosen to handle this. Other plugins should also adapt to this as it is now the "official" file type.

See [here](https://github.com/vim/vim/issues/4830) for the (somewhat lengthy) discussion that led to this result.

**Comment by chris542** [comment]
Thanks for the clear explanation.

I found that typescriptreact is also used more after commenting, but couldnt find this post.. oops. Thanks for responding 👍
