### ISSUE TITLE
About File .vue

### ISSUE THREAD

**Issue by pphboy** [preservim/nerdcommenter#457]
Unable to function properly in VUE

**Comment by pphboy** [comment]
The vue comes in four programming languages
javascript,typescript,html,css,and css kid

**Comment by alerque** [comment]
I'm not exactly sure what you are saying is the problem here. I'm guessing this is *yet another* instance of #17. If that's not what you need for this, perhaps this is similar to the React snafu where canonical VIM `filetype` setting isn't what you are using? (see #393 and various linked issues)
