### ISSUE TITLE
Malicious vim plugin that uses almost the same name

### ISSUE THREAD

**Issue by maarten0912** [preservim/nerdcommenter#468]
I accidentally tried to install the vim plugin 'preservervim/nerdcommenter' and when installing it gave the popup to log into GitHub. I suspect that this is a malicious plugin using the fact that people make typos. I have no idea where and if I can report this somewhere?

**Comment by alerque** [comment]
If the plugin existed on that typo you could find it [here](https://github.com/preservervim/nerdcommenter) and there would be a place to report it to GitHub as malicious. They do pretty fast take-downs on bad repos if you report them right.

However I don't believe there is anything going on here except your typo. When you to a `git clone` to an https url and it does not find a repo, it assumes that it might be private and that you need permission to login to see it. Hence you could probably write any old gibberish that is not a valid repository and run into the same login prompt. GitHub just assumes there might be a repository there that you can't see unless you are authenticated.
