### ISSUE TITLE
`commentstring` value is not updated after first usage in the buffer

### ISSUE THREAD

**Issue by MuhammadSawalhy** [preservim/nerdcommenter#477]
[suy/vim-context-commentstring](https://github.com/suy/vim-context-commentstring) fixes the issue of **Lue in VimScript** and [this issue of **HTML**](https://github.com/preservim/nerdcommenter/issues/17) by changing the `commentstring` value, but another issue appeared after using this, I think **nerdcommenter** stores the first use of `commentstring` in the current buffer and never read it again:

https://user-images.githubusercontent.com/42011920/129219251-a0862097-5831-4f09-960b-e1a070a43999.mp4

_Originally posted by @MuhammadSawalhy in https://github.com/preservim/nerdcommenter/issues/17#issuecomment-897709359_

**Comment by MuhammadSawalhy** [comment]
Here is another powerful plugin: https://github.com/JoosepAlviste/nvim-ts-context-commentstring

**Comment by alerque** [comment]
Is there any kind of event hook we can use to trigger a re-read when this changes? Or would we just have to never cache it? If the latter, should this be optional or default behavior?

**Comment by and3rson** [comment]
I think caching should be disabled whatsoever and commentstring should be used every time, seems like the most intuitive behavior.

**Comment by MuhammadSawalhy** [comment]
> I think caching should be disabled whatsoever and commentstring should be used every time, seems like the most intuitive behavior.

Same opinion, we have some files that contain multiple contexts that we will continuously switch between them. HTML is a well known scenario. So, `commentstring` has to be queried each time we want to comment. Some lua-based neovim commenting plugins have a hook function that updated the `commentstring` before commenting.

**Comment by alerque** [comment]
Fair enough. Happy to accept a PR that contributes that change ... otherwise it will sit on my todo list until I have a spare few minutes.

**Comment by ppwwyyxx** [comment]
I use this hook to prevent the cache. It will automatically get called by NERDCommenter.
```
function NERDCommenter_before()
  if &ft == 'vim'
    let b:NERDCommenterDelims = {
          \ 'left': matchstr(&commentstring, '^\S*\ze\s*%s'),
          \ 'right': matchstr(&commentstring, '%s\s*\zs.*$'),
          \ 'nested': 0,
          \ 'leftAlt': '',
          \ 'rightAlt': '',
          \ 'nestedAlt': 0}
  endif
endfunc
```

with this function + https://github.com/JoosepAlviste/nvim-ts-context-commentstring + #513, I can get NerdCommenter to work correctly for embedded lua inside vimscript.

**Comment by alerque** [comment]
Re-opening because I reverted #514 for now (causing other problems).
