### ISSUE TITLE
Fortran is not supported

### ISSUE THREAD

**Issue by Sunbuyu** [preservim/nerdcommenter#500]
Could you please add Fortran support? Fortran is often used in hpc, which involves high demand for this. Thanks a lot.

**Comment by Sunbuyu** [comment]
Sorry, I replaced '.f90' with '.F90' and it works now.

**Comment by alerque** [comment]
This plugin doesn't deal with suffixes or anything, it just goes by what the VIM `filetype` setting is. You could look into what is being used to detect fortran and whether the file extension should be case sensitive or not, but that's going to be in either VIM core runtimes or some other plugin, not this one.

**Comment by Sunbuyu** [comment]
Thanks!

**Comment by Sunbuyu** [comment]
> This plugin doesn't deal with suffixes or anything, it just goes by what the VIM `filetype` setting is. You could look into what is being used to detect fortran and whether the file extension should be case sensitive or not, but that's going to be in either VIM core runtimes or some other plugin, not this one.

Thanks.
