### ISSUE TITLE
infinite recursion when trying to comment glsl code

### ISSUE THREAD

**Issue by minoaut** [preservim/nerdcommenter#518]
Lately I'm getting a screen filling error message in vim whenever I try to comment shader code.

![infinite recursion](https://user-images.githubusercontent.com/100795439/236773598-ed8ca1eb-67c4-4cae-acb6-d51febb78815.png)

I have this in .vimrc:
```    Plug 'preservim/nerdcommenter'
        let g:NERDRemoveExtraSpaces = 1
        let g:NERDAltDelims_gsl = 1
        let g:NERDCustomDelimiters = { 'gsl': { 'left': '//' }, 'glslx': { 'left': '//' }  }
```

git bisect found this commit
https://github.com/preservim/nerdcommenter/commit/91499c76a7358b10945c50173fa8c64dc3c909c8

When I revert this the problem is gone.

**Comment by alerque** [comment]
@ppwwyyxx Does this ring a bell? I remember in #514 we tried to fix something, but it caused issues for me and others so we reverted it, then in #515 put in a modified fix. This is working for me (NeoVIM & the languages I work with) but apparently it is still causing issues for some folks. Any ideas?

**Comment by ppwwyyxx** [comment]
@minoaut could you try if #519 can fix it? If not, I'll need to know more about how to exactly reproduce your issue.

**Comment by alerque** [comment]
@minoaut I think @ppwwyyxx found and fixed the issue for you, you can update and give it a shot now.

**Comment by minoaut** [comment]
Yep, can confirm, after resetting the tree and updating the error is gone. That was quick, thank you both. NERD Commenter is awesome!
